### ISSUE TITLE
Error in "esx_advancedgarage"

### ISSUE THREAD

**Issue by WulferGaming** [HumanTree92/VENT_ESX_Scripts#13]
**Questions**
Which Script are you having Issues with?: esx_advancedgarage
Have you made changes to anything besides the `config.lua`?: No
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: No
What Verison of ESX Legacy are you using?: 1.7.5
Are you using OneSync?: Yes
Linux or Windows?: Windows

**Describe the Bug | A Clear & Concise Description of the Bug**
When I buy a new vehicle and want to park them, then I became this error
![Screenshot_9](https://user-images.githubusercontent.com/58594707/178147506-1914f560-b139-40f3-87c2-59de980454a9.png)
r

**Comment by HumanTree92** [comment]
Have you gotten this figured out or is it still a problem?

**Comment by KostaZx** [comment]
> Have you gotten this figured out or is it still a problem?

i have the same issue

**Comment by HumanTree92** [comment]
Try this and LMK https://github.com/HumanTree92/VENT_ESX_Scripts/commit/51fea8000f98713bf72d2e649da9f00d33a90775
