### ISSUE TITLE
Vehicle Bug in advancedvehicleshop

### ISSUE THREAD

**Issue by karlupo** [HumanTree92/VENT_ESX_Scripts#15]
**Questions**
Which Script are you having Issues with?:  esx_advancedvehicleshop
Have you made changes to anything besides the `config.lua`?: no
Have you looked through the Closed Topics?: yes
Have you looked through the Wiki?: yes
Are you using a Pre-Installed ESX? If Yes who?: ?
What Verison of ESX Legacy are you using?: es_extended
Are you using OneSync?: yes
Linux or Windows?: Linux

**Describe the Bug | A Clear & Concise Description of the Bug**
When I scroll through the vehicles and categories fastly, some vehicles stay there and won't despawn, even if I leave the vehicleshop. See Screenshots:
<img width="868" alt="image" src="https://user-images.githubusercontent.com/73790544/181904787-c302712c-6204-465c-98ff-454ecd25f0d1.png">
<img width="273" alt="image" src="https://user-images.githubusercontent.com/73790544/181904848-dd04950e-a9ff-46b4-aa5d-b3c95778e2c1.png">

**Comment by HumanTree92** [comment]
There is no easy way of fixing this. Just don't go to fast. The Script can only handle a certain amount. This is just a Basic ESX Script. If you want something that won't have this problem you would need to find a Paid Vehicle Shop. 

Both esx_vehicleshop made by the ESX Team and my Script will have this problem.
