### ISSUE TITLE
esx_advancedjail error

### ISSUE THREAD

**Issue by Svenhr** [HumanTree92/VENT_ESX_Scripts#16]
**Questions**
Which Script are you having Issues with?: esx_advancedjail 
Have you made changes to anything besides the `config.lua`?: no
Have you looked through the Closed Topics?: cant find
Have you looked through the Wiki?: there is no fix for this
Are you using a Pre-Installed ESX? If Yes who?: i donwloaded from esx-legacy latest version all is working just jail not work
What Verison of ESX Legacy are you using?: 1.7.5
Are you using OneSync?: yes
Linux or Windows?: Windows

**Describe the Bug | A Clear & Concise Description of the Bug**

Type /jail id time and player go in jail but error show in server console here is link from screenshot: https://ibb.co/1Kwj7Rn

**Comment by HumanTree92** [comment]
Try this and let me know if there is any more errors https://github.com/HumanTree92/VENT_ESX_Scripts/commit/a6f205c3abed0d54f17f24126698724e14f44af1

**Comment by Svenhr** [comment]
Hi thanks for fast response i changed it to core at line 211 in server main and new error opo up SCRIPT ERROR: @esx_advancedjail/server/main.lua:211: attempt to index a nil value (global 'Core')

**Comment by HumanTree92** [comment]
Just remove Core.SavePlayer for some reason the new Team doesn't want people to be able to execute the Save Player function from other scripts.

**Comment by Svenhr** [comment]
so need complete remove line 211 ?

**Comment by HumanTree92** [comment]
Yup just like this https://github.com/HumanTree92/VENT_ESX_Scripts/commit/9f9b5b51a52442f526d5caeb55317f09fc5c0ede

**Comment by Svenhr** [comment]
Thanks alot now no single erroe keep up good work have nice day
