### ISSUE TITLE
esx_advancedgarages categories

### ISSUE THREAD

**Issue by SkippyJeBorec** [HumanTree92/VENT_ESX_Scripts#18]
**Questions**
Which Script are you having Issues with?: esx_advancedgarages
Have you made changes to anything besides the `config.lua`?: no
Have you looked through the Closed Topics?: yes
Have you looked through the Wiki?: yes
Are you using a Pre-Installed ESX? If Yes who?: yes, esx legacy
What Verison of ESX Legacy are you using?: newest 
Are you using OneSync?: ni
Linux or Windows?: windows

**Describe the Bug | A Clear & Concise Description of the Bug**
Hey, I was just wondering if there is anyway to delete the categories of cars in garages, because my addon cars are not working. I saw a issue where somebody explained how to create new category, but I want to delete them.

**Comment by HumanTree92** [comment]
Just follow this guide https://github.com/HumanTree92/VENT_ESX_Scripts/wiki/ESX-Advanced-Garage#adding-categories but in reverse. I do not help with editing my scripts.
