### ISSUE TITLE
Cant open a bank

### ISSUE THREAD

**Issue by zRxnx** [HumanTree92/VENT_ESX_Scripts#20]
**Questions**
Which Script are you having Issues with?: esx_advancedholdup
Have you made changes to anything besides the `config.lua`?: No
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: ESX Legacy
What Verison of ESX Legacy are you using?: 1.7.5
Are you using OneSync?: Yes
Linux or Windows?: 
Linux
**Describe the Bug | A Clear & Concise Description of the Bug**
I am the only one on the server with the police job and i cant open a bank.
No rob ongoing, nothing.
I get this message "error_robbery" (in translated form)

**Comment by HumanTree92** [comment]
Config.CoolDown = 20 is the problem. Not really a problem. When the script first starts it prevents people from using the banks for 20min but people are able to use the ATMs. Once the 20min timer is up then people are allowed to use the bank. Most times when a server is coming back up from a restart nobody is on the server. But you can do this command https://github.com/HumanTree92/VENT_ESX_Scripts/blob/main/esx_advancedholdup/server/main.lua#L21 and it will reset the time back to 0

**Comment by HumanTree92** [comment]
I have now added a Config Option to be able to disable the Cool Down when server starts. https://github.com/HumanTree92/VENT_ESX_Scripts/commit/40c0f1a9e9a306ff25cdebc187a6d1205af479ea
