### ISSUE TITLE
ESX_Advancedvehicleshop Customers are freezed and invisible after buying car

### ISSUE THREAD

**Issue by SHOKiDOKi** [HumanTree92/VENT_ESX_Scripts#21]
**Questions**
Which Script are you having Issues with?: ESX_Advancedvehicleshop
Have you made changes to anything besides the `config.lua`?: NO
Have you looked through the Closed Topics?:  YES
Have you looked through the Wiki?: YES
Are you using a Pre-Installed ESX? If Yes who?: ESX Legacy 1.5.0 
What Verison of ESX Legacy are you using?: 1.5.0
Are you using OneSync?: YES
Linux or Windows?: Linux

The Player who are buying cars are invisible and freezed.
So they spawn invisible and freezed in the Car after the buying process.

**Comment by HumanTree92** [comment]
Well thats not possible. My guess is you have another Script that is conflicting. I suggest making sure you are NOT using esx_vehicleshop. Also try to use esx_vehicleshop besides esx_advancedvehicleshop and see if it works.

**Comment by SHOKiDOKi** [comment]
We are using advancedgarages so we need to use advancedvehicleshop.

I don't know which script's cause a freeze when you buy a car.. :/

**Comment by HumanTree92** [comment]
Has this been fixed? If not can you please send me an image of your owned_vehicles tables.

**Comment by SHOKiDOKi** [comment]
We just use the normal esx_vehicleshop now it works fine.

**Comment by HumanTree92** [comment]
Yeah thats weird. B/c the code for buying a vehicle is pretty much exactly the same for both esx_vehicleshop and esx_advancedvehicleshop
