### ISSUE TITLE
Access denied for user 'My user' to database 'es_extended (Can't buy a car also)

### ISSUE THREAD

**Issue by Ukimud** [HumanTree92/VENT_ESX_Scripts#24]
**Questions**
Which Script are you having Issues with?: esx_advancedvehicleshop
Have you made changes to anything besides the `config.lua`?: locales, just translated everything to my language
Have you looked through the Closed Topics?: yes
Have you looked through the Wiki?: yes
Are you using a Pre-Installed ESX? If Yes who?: 
What Version of ESX Legacy are you using?: the latest
Are you using OneSync?: Yes
Linux or Windows?:  Windows

**Describe the Bug | A Clear & Concise Description of the Bug**
when i try to add the sql to my database my database says "Access denied for user 'My user' to database 'es_extended'
So, it adds the vs_cars and everything else but when i buy somehing off the car shop it wont buy it, i have your garage on my server too and all the requirements needed

**Comment by HumanTree92** [comment]
Have you figured this out. Access Denied for user is a you problem. This isn't something that can be fixed on my end.
