### ISSUE TITLE
Bug Report - esx_advancedvehicleshop

### ISSUE THREAD

**Issue by Cluts** [HumanTree92/VENT_ESX_Scripts#26]
**Questions**
Which Script are you having Issues with?: 
esx_advancedvehicleshop
Have you made changes to anything besides the `config.lua`?: 
No
Have you looked through the Closed Topics?: 
Yes
Have you looked through the Wiki?: 
Yes
Are you using a Pre-Installed ESX? If Yes who?: 
Yes, ESX Legacy 1.8.5
What Verison of ESX Legacy are you using?: 
1.8.5
Are you using OneSync?: 
Yes
Linux or Windows?: 
Windows

**Describe the Bug | A Clear & Concise Description of the Bug**
This happens whenever I try to buy a car in : policejob, ambulancejob, mechanicjob. (doesn't happen in taxi shop but menu item appears as "undefined" instead of "Taxi" (As label is set in config.lua).
![image](https://user-images.githubusercontent.com/6239217/209533725-9f526973-9e96-461f-a513-d53b8ad60876.png)
No errors in console.
This is what my SQL Looks like:
![image](https://user-images.githubusercontent.com/6239217/209533805-2e6ebf22-ed19-4bc5-a27d-96100f20f2e5.png)
and this is what the code at that line number looks like:
![image](https://user-images.githubusercontent.com/6239217/209533853-823a998e-258f-408e-a203-c35c7db1a181.png)

I was thinking I should modify "sVehicles" into another variable, but I didn't wanna mess it up more than it is lol, I already did everything that readme.txt said in order to make this script work with police & ambulance job, but this still happens with mechanicjob also. I think there's a problem when "buying" the car instead of "spawn" the car (like taxi job).

Thanks in advance! 
Cluts.-

**Comment by HumanTree92** [comment]
# How to use Ambulance, Police, Mechanic, & Taxi Shop
1) For `vs_ambulance_categories` & `vs_police_categories` & `vs_mechanic_categories` & `vs_taxi_categories`
  * The column `name` should be the job_grades name
  * The column `label` should be the job_grades label
2) For `vs_ambulance` & `vs_police` & `vs_mechanic` & `vs_taxi`
  * The column `id` should start at 1 and so on.
  * The column `name` should be the vehicle name.
  * The column `model` should be spawn name.
  * The column `price` should be the vehicles price.
  * The column `category` should be the job_grades name
3) You can find Examples in the `esx_advancedvehicleshop.sql`
