### ISSUE TITLE
I can't use any item, I'm using the default inventory and I don't get any errors in the console esx_extraitems

### ISSUE THREAD

**Issue by zelectrih** [HumanTree92/VENT_ESX_Scripts#3]
**Questions**
Which Script are you having Issues with?: esx_extraitems
Have you made changes to anything besides the `config.lua`?: No
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: No
Are you using ESX Legacy V1.3 Final?: Yes
Are you using OneSync?: Yes
Linux or Windows?: Windows

**Describe the Bug | A Clear & Concise Description of the Bug**
I
![unknown](https://user-images.githubusercontent.com/78527956/158546585-4bc39abe-9c31-434c-acdf-8bbcdbddd980.png)
 can't use any item, I'm using the default inventory and I don't get any errors in the console

**Comment by HumanTree92** [comment]
Sorry. Was going to PM you on Discord. Did you get this fixed? If you have a way of showing you how much armor you have when you use the item it should work.

This is the client side of the Bulletproof Vests:
RegisterNetEvent('esx_extraitems:bulletproof')
AddEventHandler('esx_extraitems:bulletproof', function()
	local playerPed = GetPlayerPed(-1)

	SetPedComponentVariation(playerPed, 9, 27, 9, 2)
	AddArmourToPed(playerPed, 100)
	SetPedArmour(playerPed, 100)
end)

Maybe try removing SetPedComponentVariation(playerPed, 9, 27, 9, 2)
