### ISSUE TITLE
Esx_AdvancedGarage sql issue

### ISSUE THREAD

**Issue by xrva** [HumanTree92/VENT_ESX_Scripts#30]
**Questions**
Which Script are you having Issues with?: esx_Advancedgarage
Have you made changes to anything besides the `config.lua`?:  no
Have you looked through the Closed Topics?: yes
Have you looked through the Wiki?: yes
Are you using a Pre-Installed ESX? If Yes who?: no
What Verison of ESX Legacy are you using?:  Latest
Are you using OneSync?: yes
Linux or Windows?: Windows

**Describe the Bug | A Clear & Concise Description of the Bug**
SCRIPT ERROR in promise (unhandled rejection): Error: garazas was unable to execute a query!
[      script:oxmysql] Table 'esxlegacy_66138d.owned_properties' doesn't exist
[      script:oxmysql] SELECT * FROM owned_properties WHERE owner = ? ["char1:90b0a31b79c5b1bc1a3ec1409af718d87570b509"]

**Comment by HumanTree92** [comment]
The fix is included in the error. 
[ script:oxmysql] Table 'esxlegacy_66138d.owned_properties' doesn't exist

Its saying that the Table isn't there.
