### ISSUE TITLE
esx_advancedvehicleshop try to change the buy currency from money to bitcoin

### ISSUE THREAD

**Issue by georgekris** [HumanTree92/VENT_ESX_Scripts#4]
**Questions**
Which Script are you having Issues with?: esx_advancedvehicleshop
Have you made changes to anything besides the `config.lua`?: yes in server.lua 
Have you looked through the Closed Topics?: ???
Have you looked through the Wiki?:  no
Are you using a Pre-Installed ESX? If Yes who?: 
Are you using ESX Legacy V1.3 Final?: 1.2 Final
Are you using OneSync?: yes
Linux or Windows?:  Windows

**Describe the Bug | A Clear & Concise Description of the Bug**

hi i try to make the vip boat shop to buy with bitcoin and i get this error

[  script:es_extended] (nil stack trace)SCRIPT ERROR: @esx_advancedvehicleshop/server/main.lua:1071: attempt to call a nil value (field 'getBitcoin')
[script:esx_advancedv] > TriggerServerCallback (@es_extended/server/functions.lua:160)
[script:esx_advancedv] > handler (@es_extended/server/common.lua:71)
[  script:es_extended] SCRIPT ERROR: error object is not a string
[  script:es_extended] (nil stack trace)

**Comment by HumanTree92** [comment]
This is not an issue with the script itself. Might i suggest looking at how other scripts use bitcoins to make purchases and just copy that method over.
