### ISSUE TITLE
BUG take out vehicles in other garages

### ISSUE THREAD

**Issue by sixenom** [HumanTree92/VENT_ESX_Scripts#6]
**Questions**
Which Script are you having Issues with?:  esx_advancedgarage
Have you made changes to anything besides the `config.lua`?:  no
Have you looked through the Closed Topics?: no
Have you looked through the Wiki?: si
Are you using a Pre-Installed ESX? If Yes who?: no
Are you using ESX Legacy V1.3 Final?: yes
Are you using OneSync?: no
Linux or Windows?: windows

that they cannot take out vehicles in other garages, I kept a vehicle in one corner of the map and went up to the other and could take it out, this lends itself to the fact that they can do anti-role by moving things from one end to the other

**Comment by HumanTree92** [comment]
At the moment yes. All garages are tied to each other. I have plans in the future to add an option to disable this. However i have been busy with a Construction Project (Building a Event Center/House) that i just don't have as much time anymore.
