### ISSUE TITLE
Cant store personal boats

### ISSUE THREAD

**Issue by lord0o** [HumanTree92/VENT_ESX_Scripts#7]
**Questions**
Which Script are you having Issues with?: esx_advancedgarage
Have you made changes to anything besides the `config.lua`?:  no
Have you looked through the Closed Topics?:  yes
Have you looked through the Wiki?:  yes
Are you using a Pre-Installed ESX? If Yes who?:  no
Are you using ESX Legacy V1.3 Final?:  yes
Are you using OneSync?:  no
Linux or Windows?:  win 10

I cant store my personal boats on boat garage. 

These are default boats that im trying to store. jetmax and longfin.

Thank you for your time.
![image_2022-05-21_134228742](https://user-images.githubusercontent.com/1349872/169661164-1febfe22-49de-4339-bc51-e8ac0699f5d6.png)

![image_2022-05-21_134413250](https://user-images.githubusercontent.com/1349872/169661229-4c55baad-ad4e-4409-84bc-0bfa07fb3919.png)

**Comment by HumanTree92** [comment]
Questions:
1. Have you figured this out yet?
2. Can you provide an image of your owned_vehicles DB?

**Comment by lord0o** [comment]
> Questions:
> 
> 1. Have you figured this out yet?
> 2. Can you provide an image of your owned_vehicles DB?

not yet, traveling for work rn. coming back to my pc in 2 weeks. i will upload the info then.

**Comment by lord0o** [comment]
> Questions:
> 
> 1. Have you figured this out yet?
> 2. Can you provide an image of your owned_vehicles DB?

![image](https://user-images.githubusercontent.com/1349872/176280338-da5a9fff-7187-4192-a5e9-b750b0819f04.png)

**Comment by HumanTree92** [comment]
Can you send me the esx_advancedgarage files you have. Just put them in a .zip and send them through here.

**Comment by lord0o** [comment]
> Can you send me the esx_advancedgarage files you have. Just put them in a .zip and send them through here.


Sure, here it is:
[esx_advancedgarage.zip](https://github.com/HumanTree92/VENT_ESX_Scripts/files/9005674/esx_advancedgarage.zip)

**Comment by HumanTree92** [comment]
Closing Issue as i haven't gotten a response in over 2 weeks.
